<?php
/**
 * @author  Nikita Kolosov <anexroid@gmail.com>
 * @license MIT License
 * @year    2016
 */

namespace Wav;

class WaveFormat
{
    const UNKNOWN = 0x0000; /* Microsoft Corporation */
    const PCM = 0x0001; /* Microsoft Corporation */
    const ADPCM = 0x0002; /* Microsoft Corporation */
    const IEEE_FLOAT = 0x0003; /* Microsoft Corporation */
    const VSELP = 0x0004; /* Compaq Computer Corp. */
    const IBM_CVSD = 0x0005; /* IBM Corporation */
    const ALAW = 0x0006; /* Microsoft Corporation */
    const MULAW = 0x0007; /* Microsoft Corporation */
    const DTS = 0x0008; /* Microsoft Corporation */
    const DRM = 0x0009; /* Microsoft Corporation */
    const OKI_ADPCM = 0x0010; /* OKI */
    const DVI_ADPCM = 0x0011; /* Intel Corporation */
    const IMA_ADPCM = 0x0011; /* Intel Corporation */
    const MEDIASPACE_ADPCM = 0x0012; /* Videologic */
    const SIERRA_ADPCM = 0x0013; /* Sierra Semiconductor Corp */
    const G723_ADPCM = 0x0014; /* Antex Electronics Corporation */
    const DIGISTD = 0x0015; /* DSP Solutions, Inc. */
    const DIGIFIX = 0x0016; /* DSP Solutions, Inc. */
    const DIALOGIC_OKI_ADPCM = 0x0017; /* Dialogic Corporation */
    const MEDIAVISION_ADPCM = 0x0018; /* Media Vision, Inc. */
    const CU_CODEC = 0x0019; /* Hewlett-Packard Company */
    const YAMAHA_ADPCM = 0x0020; /* Yamaha Corporation of America */
    const SONARC = 0x0021; /* Speech Compression */
    const DSPGROUP_TRUESPEECH = 0x0022; /* DSP Group, Inc */
    const ECHOSC1 = 0x0023; /* Echo Speech Corporation */
    const AUDIOFILE_AF36 = 0x0024; /* Virtual Music, Inc. */
    const APTX = 0x0025; /* Audio Processing Technology */
    const AUDIOFILE_AF10 = 0x0026; /* Virtual Music, Inc. */
    const PROSODY_1612 = 0x0027; /* Aculab plc */
    const LRC = 0x0028; /* Merging Technologies S.A. */
    const DOLBY_AC2 = 0x0030; /* Dolby Laboratories */
    const GSM610 = 0x0031; /* Microsoft Corporation */
    const MSNAUDIO = 0x0032; /* Microsoft Corporation */
    const ANTEX_ADPCME = 0x0033; /* Antex Electronics Corporation */
    const CONTROL_RES_VQLPC = 0x0034; /* Control Resources Limited */
    const DIGIREAL = 0x0035; /* DSP Solutions, Inc. */
    const DIGIADPCM = 0x0036; /* DSP Solutions, Inc. */
    const CONTROL_RES_CR10 = 0x0037; /* Control Resources Limited */
    const NMS_VBXADPCM = 0x0038; /* Natural MicroSystems */
    const CS_IMAADPCM = 0x0039; /* Crystal Semiconductor IMA ADPCM */
    const ECHOSC3 = 0x003A; /* Echo Speech Corporation */
    const ROCKWELL_ADPCM = 0x003B; /* Rockwell International */
    const ROCKWELL_DIGITALK = 0x003C; /* Rockwell International */
    const XEBEC = 0x003D; /* Xebec Multimedia Solutions Limited */
    const G721_ADPCM = 0x0040; /* Antex Electronics Corporation */
    const G728_CELP = 0x0041; /* Antex Electronics Corporation */
    const MSG723 = 0x0042; /* Microsoft Corporation */
    const MPEG = 0x0050; /* Microsoft Corporation */
    const RT24 = 0x0052; /* InSoft, Inc. */
    const PAC = 0x0053; /* InSoft, Inc. */
    const MPEGLAYER3 = 0x0055; /* ISO/MPEG Layer3 Format Tag */
    const LUCENT_G723 = 0x0059; /* Lucent Technologies */
    const CIRRUS = 0x0060; /* Cirrus Logic */
    const ESPCM = 0x0061; /* ESS Technology */
    const VOXWARE = 0x0062; /* Voxware Inc */
    const CANOPUS_ATRAC = 0x0063; /* Canopus, co., Ltd. */
    const G726_ADPCM = 0x0064; /* APICOM */
    const G722_ADPCM = 0x0065; /* APICOM */
    const DSAT_DISPLAY = 0x0067; /* Microsoft Corporation */
    const VOXWARE_BYTE_ALIGNED = 0x0069; /* Voxware Inc */
    const VOXWARE_AC8 = 0x0070; /* Voxware Inc */
    const VOXWARE_AC10 = 0x0071; /* Voxware Inc */
    const VOXWARE_AC16 = 0x0072; /* Voxware Inc */
    const VOXWARE_AC20 = 0x0073; /* Voxware Inc */
    const VOXWARE_RT24 = 0x0074; /* Voxware Inc */
    const VOXWARE_RT29 = 0x0075; /* Voxware Inc */
    const VOXWARE_RT29HW = 0x0076; /* Voxware Inc */
    const VOXWARE_VR12 = 0x0077; /* Voxware Inc */
    const VOXWARE_VR18 = 0x0078; /* Voxware Inc */
    const VOXWARE_TQ40 = 0x0079; /* Voxware Inc */
    const SOFTSOUND = 0x0080; /* Softsound, Ltd. */
    const VOXWARE_TQ60 = 0x0081; /* Voxware Inc */
    const MSRT24 = 0x0082; /* Microsoft Corporation */
    const G729A = 0x0083; /* AT&amp;T Labs, Inc. */
    const MVI_MVI2 = 0x0084; /* Motion Pixels */
    const DF_G726 = 0x0085; /* DataFusion Systems (Pty) (Ltd) */
    const DF_GSM610 = 0x0086; /* DataFusion Systems (Pty) (Ltd) */
    const ISIAUDIO = 0x0088; /* Iterated Systems, Inc. */
    const ONLIVE = 0x0089; /* OnLive! Technologies, Inc. */
    const SBC24 = 0x0091; /* Siemens Business Communications Sys */
    const DOLBY_AC3_SPDIF = 0x0092; /* Sonic Foundry */
    const MEDIASONIC_G723 = 0x0093; /* MediaSonic */
    const PROSODY_8KBPS = 0x0094; /* Aculab plc */
    const ZYXEL_ADPCM = 0x0097; /* ZyXEL Communications, Inc. */
    const PHILIPS_LPCBB = 0x0098; /* Philips Speech Processing */
    const PACKED = 0x0099; /* Studer Professional Audio AG */
    const MALDEN_PHONYTALK = 0x00A0; /* Malden Electronics Ltd. */
    const RHETOREX_ADPCM = 0x0100; /* Rhetorex Inc. */
    const IRAT = 0x0101; /* BeCubed Software Inc. */
    const VIVO_G723 = 0x0111; /* Vivo Software */
    const VIVO_SIREN = 0x0112; /* Vivo Software */
    const DIGITAL_G723 = 0x0123; /* Digital Equipment Corporation */
    const SANYO_LD_ADPCM = 0x0125; /* Sanyo Electric Co., Ltd. */
    const SIPROLAB_ACEPLNET = 0x0130; /* Sipro Lab Telecom Inc. */
    const SIPROLAB_ACELP4800 = 0x0131; /* Sipro Lab Telecom Inc. */
    const SIPROLAB_ACELP8V3 = 0x0132; /* Sipro Lab Telecom Inc. */
    const SIPROLAB_G729 = 0x0133; /* Sipro Lab Telecom Inc. */
    const SIPROLAB_G729A = 0x0134; /* Sipro Lab Telecom Inc. */
    const SIPROLAB_KELVIN = 0x0135; /* Sipro Lab Telecom Inc. */
    const G726ADPCM = 0x0140; /* Dictaphone Corporation */
    const QUALCOMM_PUREVOICE = 0x0150; /* Qualcomm, Inc. */
    const QUALCOMM_HALFRATE = 0x0151; /* Qualcomm, Inc. */
    const TUBGSM = 0x0155; /* Ring Zero Systems, Inc. */
    const MSAUDIO1 = 0x0160; /* Microsoft Corporation */
    const UNISYS_NAP_ADPCM = 0x0170; /* Unisys Corp. */
    const UNISYS_NAP_ULAW = 0x0171; /* Unisys Corp. */
    const UNISYS_NAP_ALAW = 0x0172; /* Unisys Corp. */
    const UNISYS_NAP_16K = 0x0173; /* Unisys Corp. */
    const CREATIVE_ADPCM = 0x0200; /* Creative Labs, Inc */
    const CREATIVE_FASTSPEECH8 = 0x0202; /* Creative Labs, Inc */
    const CREATIVE_FASTSPEECH10 = 0x0203; /* Creative Labs, Inc */
    const UHER_ADPCM = 0x0210; /* UHER informatic GmbH */
    const QUARTERDECK = 0x0220; /* Quarterdeck Corporation */
    const ILINK_VC = 0x0230; /* I-link Worldwide */
    const RAW_SPORT = 0x0240; /* Aureal Semiconductor */
    const ESST_AC3 = 0x0241; /* ESS Technology, Inc. */
    const IPI_HSX = 0x0250; /* Interactive Products, Inc. */
    const IPI_RPELP = 0x0251; /* Interactive Products, Inc. */
    const CS2 = 0x0260; /* Consistent Software */
    const SONY_SCX = 0x0270; /* Sony Corp. */
    const FM_TOWNS_SND = 0x0300; /* Fujitsu Corp. */
    const BTV_DIGITAL = 0x0400; /* Brooktree Corporation */
    const QDESIGN_MUSIC = 0x0450; /* QDesign Corporation */
    const VME_VMPCM = 0x0680; /* AT&amp;T Labs, Inc. */
    const TPC = 0x0681; /* AT&amp;T Labs, Inc. */
    const OLIGSM = 0x1000; /* Ing C. Olivetti &amp; C., S.p.A. */
    const OLIADPCM = 0x1001; /* Ing C. Olivetti &amp; C., S.p.A. */
    const OLICELP = 0x1002; /* Ing C. Olivetti &amp; C., S.p.A. */
    const OLISBC = 0x1003; /* Ing C. Olivetti &amp; C., S.p.A. */
    const OLIOPR = 0x1004; /* Ing C. Olivetti &amp; C., S.p.A. */
    const LH_CODEC = 0x1100; /* Lernout &amp; Hauspie */
    const NORRIS = 0x1400; /* Norris Communications, Inc. */
    const SOUNDSPACE_MUSICOMPRESS = 0x1500; /* AT&amp;T Labs, Inc. */
    const DVM = 0x2000; /* FAST Multimedia AG */
}